In [15]:
import csv, statistics

In [21]:
def calculate_rating_stats(data, industry = None):
    rating = []
    for row in data:
        if row[3]!='NULL' and (not industry or row[1] == industry):
            rating.append(float(row[3]))
    max_rating = max(rating)
    min_rating = min(rating)
    mean_rating = statistics.mean(rating)
    return max_rating, min_rating, mean_rating

In [35]:
with open("movies.csv") as f:
    data = list(csv.reader(f))
    header = data[0]
    data = data[1:]
max_rating, min_rating, mean_rating = calculate_rating_stats(data)
print(f"All records: Max rating = {max_rating}, Min rating = {min_rating}, and Avg rating = {mean_rating}. \n")

max_rating, min_rating, mean_rating = calculate_rating_stats(data, industry = "Bollywood")
print(f"Bollywood : Max rating = {max_rating}, Min rating = {min_rating}, and Avg rating = {mean_rating}. \n")

max_rating, min_rating, mean_rating = calculate_rating_stats(data, industry = "Hollywood")
print(f"Hollywood : Max rating = {max_rating}, Min rating = {min_rating}, and Avg rating = {mean_rating}.")

All records: Max rating = 9.3, Min rating = 1.9, and Avg rating = 7.919444444444444.

Bollywood : Max rating = 8.4, Min rating = 1.9, and Avg rating = 7.65625.

Hollywood : Max rating = 9.3, Min rating = 6.8, and Avg rating = 8.13.

# The Another way is by using Pandas Library

In [39]:
!pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [41]:
import pandas as pd

In [45]:
df = pd.read_csv("movies.csv")
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [50]:
print(df.imdb_rating)

0     8.3
1     7.0
2     6.8
3     7.9
4     6.8
5     9.3
6     8.6
7     8.0
8     8.5
9     7.9
10    8.6
11    7.8
12    9.2
13    9.0
14    9.0
15    8.2
16    8.5
17    8.4
18    8.4
19    6.9
20    7.8
21    8.0
22    8.4
23    7.4
24    7.2
25    8.3
26    8.1
27    8.1
28    NaN
29    8.3
30    8.1
31    1.9
32    8.4
33    8.4
34    7.6
35    8.0
36    8.0
Name: imdb_rating, dtype: float64

In [60]:
df.imdb_rating.mean(), df.imdb_rating.max(), df.imdb_rating.min()

(7.919444444444445, 9.3, 1.9)

In [74]:
df_bollywood = df[df.industry == 'Bollywood']
df_hollywood = df[df.industry == 'Hollywood']

In [78]:
df_bollywood

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.0,2000.0,Millions,INR,Hindi
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.4,3.5,Billions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.0,8540.0,Millions,INR,Hindi
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.0,5.9,Billions,INR,Hindi
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.0,3409.0,Millions,INR,Hindi
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.0,11690.0,Millions,INR,Hindi
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [80]:
df_bollywood.imdb_rating.mean(), df_bollywood.imdb_rating.max(), df_bollywood.imdb_rating.min()

(7.656250000000001, 8.4, 1.9)

In [82]:
df_hollywood.imdb_rating.mean(), df_hollywood.imdb_rating.max(), df_hollywood.imdb_rating.min()

(8.130000000000003, 9.3, 6.8)